# III. Methodology: Code

### Setup

In [1]:
# Import modules
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

## 1. Data Preprocessing

In [2]:
header_names = ['Symbol',
 'Date',
 'Open',
 'High',
 'Low',
 'Close',
 'Volume',
 'Ex-Dividend',
 'Split Ratio',
 'Adj. Open',
 'Adj. High',
 'Adj. Low',
 'Adj. Close',
 'Adj. Volume']

In [3]:
# Read HUGE csv that has all the daily LSE data from 1977
# Data Preprocessing: adding header to CSV
df = pd.read_csv('~/lse-data/lse/WIKI_20160909.csv', header=None, names=header_names)

### 1.1 Examining Abnormalities

Need to investigate previous observation that Opening, High, Low, Close prices have minimum of 0.

In [9]:
df[df['Open'] == 0]
#['Symbol'].unique()

,Symbol,Date,Open,High,Low,Close,Volume,Ex-Dividend,Split Ratio,Adj. Open,Adj. High,Adj. Low,Adj. Close,Adj. Volume
1047193,ARWR,2002-10-11,0.0,0.00,0.0,0.00,65000.0,0.0,1.0,0.0,0.00,0.0,0.000000,100.000000
1047194,ARWR,2002-10-14,0.0,0.00,0.0,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.000000,0.000000
1047195,ARWR,2002-10-15,0.0,0.00,0.0,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.000000,0.000000
1047196,ARWR,2002-10-16,0.0,0.00,0.0,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.000000,0.000000
1047197,ARWR,2002-10-17,0.0,0.00,0.0,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.000000,0.000000
1047198,ARWR,2002-10-18,0.0,0.00,0.0,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.000000,0.000000
1047199,ARWR,2002-10-21,0.0,0.00,0.0,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.000000,0.000000
1047200,ARWR,2002-10-22,0.0,0.00,0.0,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.000000,0.000000
7608936,LFVN,2003-02-21,0.0,0.01,0.0,0.01,27200.0,0.0,1.0,0.0,4.76,0.0,4.760000,57.142857
7608983,LFVN,2003-04-30,0.0,0.00,0.0,0.00,6800.0,0.0,1.0,0.0,0.00,0.0,0.000000,14.285714
7608984,LFVN,2003-05-01,0.0,0.00,0.0,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.000000,0.000000
7608985,LFVN,2003-05-02,0.0,0.00,0.0,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.000000,0.000000
7608986,LFVN,2003-05-05,0.0,0.00,0.0,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.000000,0.000000
7608987,LFVN,2003-05-06,0.0,0.00,0.0,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.000000,0.000000
7608988,LFVN,2003-05-07,0.0,0.00,0.0,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.000000,0.000000
7608989,LFVN,2003-05-08,0.0,0.00,0.0,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.000000,0.000000
7608990,LFVN,2003-05-09,0.0,0.00,0.0,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.000000,0.000000
7608991,LFVN,2003-05-12,0.0,0.00,0.0,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.000000,0.000000
7608992,LFVN,2003-05-13,0.0,0.00,0.0,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.000000,0.000000
9330994,NUTR,2008-09-12,0.0,0.00,0.0,12.15,0.0,0.0,1.0,0.0,0.00,0.0,11.426355,0.000000
13614062,VTNR,2002-01-25,0.0,0.00,0.0,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.000000,0.000000
13614063,VTNR,2002-01-28,0.0,0.00,0.0,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.000000,0.000000
13614064,VTNR,2002-01-29,0.0,0.00,0.0,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.000000,0.000000
13614065,VTNR,2002-01-30,0.0,0.00,0.0,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.000000,0.000000
13614066,VTNR,2002-01-31,0.0,0.00,0.0,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.000000,0.000000
13614067,VTNR,2002-02-01,0.0,0.00,0.0,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.000000,0.000000
13614068,VTNR,2002-02-04,0.0,0.00,0.0,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.000000,0.000000
13614069,VTNR,2002-02-05,0.0,0.00,0.0,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.000000,0.000000
13614070,VTNR,2002-02-06,0.0,0.00,0.0,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.000000,0.000000
13614071,VTNR,2002-02-07,0.0,0.00,0.0,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13614242,VTNR,2002-10-11,0.0,0.00,0.0,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.000000,0.000000
13614243,VTNR,2002-10-14,0.0,0.00,0.0,0.00,48000.0,0.0,1.0,0.0,0.00,0.0,0.000000,800.000000
13614244,VTNR,2002-10-15,0.0,0.00,0.0,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.000000,0.000000
13614245,VTNR,2002-10-16,0.0,0.00,0.0,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.000000,0.000000
13614246,VTNR,2002-10-17,0.0,0.00,0.0,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.000000,0.000000
13614247,VTNR,2002-10-18,0.0,0.00,0.0,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.000000,0.000000
13614248,VTNR,2002-10-21,0.0,0.00,0.0,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.000000,0.000000
13614249,VTNR,2002-10-22,0.0,0.00,0.0,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.000000,0.000000
13614250,VTNR,2002-10-23,0.0,0.00,0.0,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.000000,0.000000
13614251,VTNR,2002-10-24,0.0,0.00,0.0,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.000000,0.000000
13614252,VTNR,2002-10-25,0.0,0.00,0.0,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.000000,0.000000
13614253,VTNR,2002-10-28,0.0,0.00,0.0,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.000000,0.000000
13614254,VTNR,2002-10-29,0.0,0.00,0.0,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.000000,0.000000
13614255,VTNR,2002-10-30,0.0,0.00,0.0,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.000000,0.000000
13614256,VTNR,2002-10-31,0.0,0.00,0.0,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.000000,0.000000
13614257,VTNR,2002-11-01,0.0,0.00,0.0,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.000000,0.000000
13614258,VTNR,2002-11-04,0.0,0.00,0.0,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.000000,0.000000
13614259,VTNR,2002-11-05,0.0,0.00,0.0,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.000000,0.000000
13614260,VTNR,2002-11-06,0.0,0.00,0.0,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.000000,0.000000
13614261,VTNR,2002-11-07,0.0,0.00,0.0,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.000000,0.000000
13614262,VTNR,2002-11-08,0.0,0.00,0.0,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.000000,0.000000
13614263,VTNR,2002-11-11,0.0,0.00,0.0,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.000000,0.000000
13614264,VTNR,2002-11-12,0.0,0.00,0.0,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.000000,0.000000
13614265,VTNR,2002-11-13,0.0,0.00,0.0,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.000000,0.000000
13614266,VTNR,2002-11-14,0.0,0.00,0.0,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.000000,0.000000
13614267,VTNR,2002-11-15,0.0,0.00,0.0,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.000000,0.000000
13614268,VTNR,2002-11-18,0.0,0.00,0.0,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.000000,0.000000
13614269,VTNR,2002-11-19,0.0,0.00,0.0,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.000000,0.000000
13614270,VTNR,2002-11-20,0.0,0.00,0.0,0.00,24000.0,0.0,1.0,0.0,0.00,0.0,0.000000,400.000000
13614271,VTNR,2002-11-21,0.0,0.02,0.0,0.02,24000.0,0.0,1.0,0.0,1.20,0.0,1.200000,400.000000

### 1.2 Feature Engineering

#### 1.2.1 Measures of variation

In [10]:
# Create additional features
# These features are not used in the current model
df.loc[:,'Daily Variation'] = df.loc[:,'High'] - df.loc[:,'Low']
df.loc[:,'Percentage Variation'] = df.loc[:,'Daily Variation'] / df.loc[:,'Open'] * 100
df.loc[:,'Adj. Daily Variation'] = df.loc[:,'Adj. High'] - df.loc[:,'Adj. Low']
df.loc[:,'Adj. Percentage Variation'] = df.loc[:,'Adj. Daily Variation'] / df.loc[:,'Adj. Open'] * 100

#### 1.2.2 Extracting specific stocks
#### 1.2.2.1 BP

In [19]:
# Extract BP data
bp = df[df['Symbol'] == 'BP']
bp.head()

,Symbol,Date,Open,High,Low,Close,Volume,Ex-Dividend,Split Ratio,Adj. Open,Adj. High,Adj. Low,Adj. Close,Adj. Volume,Daily Variation,Percentage Variation,Adj. Daily Variation,Adj. Percentage Variation
1923099,BP,1977-01-03,76.50,77.62,76.50,77.62,12400.0,0.0,1.0,1.990787,2.019933,1.990787,2.019933,198400.0,1.12,1.464052,0.029146,1.464052
1923100,BP,1977-01-04,77.62,78.00,76.75,77.00,19300.0,0.0,1.0,2.019933,2.029822,1.997292,2.003798,308800.0,1.25,1.610410,0.032529,1.610410
1923101,BP,1977-01-05,77.00,77.00,74.50,74.50,17900.0,0.0,1.0,2.003798,2.003798,1.938740,1.938740,286400.0,2.50,3.246753,0.065058,3.246753
1923102,BP,1977-01-06,74.50,75.50,74.50,75.12,23900.0,0.0,1.0,1.938740,1.964763,1.938740,1.954874,382400.0,1.00,1.342282,0.026023,1.342282
1923103,BP,1977-01-07,75.12,75.38,74.62,75.12,41700.0,0.0,1.0,1.954874,1.961640,1.941863,1.954874,667200.0,0.76,1.011715,0.019778,1.011715

#### 1.2.2.2 Stocks that are in the same group as BP:

Found using the LSE stocks list (supplementary data source).

# Company names and stock symbols
China Petroleum and Chemical Corp: SNP,
GAIL (India): GAIA or GAID,
Gazprom: GAZ or 81jk or OGZD,
Green Dragon Gas Ltd: GDG,
Hellenic Petroleum SA: 98LQ or HLPD,
Lukoil PJSC: LKOE, LKOD or LKOH,
Magyar Olaj-es Gazipare Reszvenytar: MOLD,
Mando Machinery Corp: MNMD or 05IS,
Rosneft Oil Co: 40XT or ROSN,
Royal Dutch Shell: RDSA or RDSB,
Sacoil Hldgs Ltd: SAC,
Surgutneftegaz: SGGD,
Tatneft PJSC: ATAD,
Total SA: TTA,
Zoltav Resources Inc: ZOL

#### 1.2.2.3 FTSE 100:

Source: Scraped from Google Finance.

In [17]:
ftse100_csv = pd.read_csv("ftse100-figures.csv")
ftse100_csv.head()

         Date     Open     High      Low    Close
0  2016-09-09  6858.70  6862.38  6762.30  6776.95
1  2016-09-08  6846.58  6889.64  6819.82  6858.70
2  2016-09-07  6826.05  6856.12  6814.87  6846.58
3  2016-09-06  6879.42  6887.92  6818.96  6826.05
4  2016-09-05  6894.60  6910.66  6867.08  6879.42

#### 1.2.3 N-day moving averages

Only applying this to specific stocks because this takes much computational power.

In [20]:
# N-day moving averages of adjusted close prices

def n_day_moving_average(df, moving_average):
    # Create a column `N-day moving Average`.
    df['%s-day Moving Average' % str(moving_average)] = 0

    for i in range(moving_average, len(bp)):
        m_average = sum(df.iloc[i-moving_average:i]['Adj. Close'])/moving_average
        df.iloc[i].loc['%s-day Moving Average' % str(moving_average)] = m_average

# n_day_moving_average(bp, 30)

## 2. Implementation

### 2.1 Build training and test sets

In [21]:
# Initialise variables
# Number of days prior that we consider
days = 7
# Number of train and test examples combined
periods = 9000

# Columns
columns = []
for j in range(1,days+1):
    columns.append('i-%s' % str(j))
columns.append('Adj. High')
columns.append('Adj. Low')
print(columns)

# Index
start_date = bp.iloc[days]["Date"]
print("Start date: ", start_date)
index = pd.date_range(start_date, periods=periods, freq='D')

# Create empty dataframes for features and prices
features = pd.DataFrame(index=index, columns=columns)
prices = pd.DataFrame(index=index, columns=["Target"])

# Prepare test and training sets
for i in range(periods):
    prices.iloc[i]['Target'] = bp.iloc[i+days]['Adj. Close']
    for j in range(days):
        features.iloc[i]['i-%s' % str(7-j)] = bp.iloc[i+j]['Adj. Close']
    features.iloc[i]['Adj. High'] = max(bp[i:i+days]['Adj. High'])
    features.iloc[i]['Adj. Low'] = min(bp[i:i+days]['Adj. Low'])
print(features.head())
print(prices.head())

['i-1', 'i-2', 'i-3', 'i-4', 'i-5', 'i-6', 'i-7', 'Adj. High', 'Adj. Low']
Start date:  1977-01-12
                i-1      i-2      i-3      i-4      i-5      i-6      i-7  \
1977-01-12  1.95175  1.96789  1.95487  1.95487  1.93874   2.0038  2.01993
1977-01-13  1.93223  1.95175  1.96789  1.95487  1.95487  1.93874   2.0038
1977-01-14  1.97777  1.93223  1.95175  1.96789  1.95487  1.95487  1.93874
1977-01-15  1.95175  1.97777  1.93223  1.95175  1.96789  1.95487  1.95487
1977-01-16  1.95826  1.95175  1.97777  1.93223  1.95175  1.96789  1.95487

           Adj. High Adj. Low
1977-01-12   2.02982  1.93874
1977-01-13   2.02982  1.91272
1977-01-14    2.0038  1.91272
1977-01-15   1.98766  1.91272
1977-01-16   1.98766  1.91272
             Target
1977-01-12  1.93223
1977-01-13  1.97777
1977-01-14  1.95175
1977-01-15  1.95826
1977-01-16  1.94863

In [22]:
# N-day prices target

# Initialise variables
target_days = 7

# Create target dataframe
nday_columns = []
for j in range(1,target_days+1):
    nday_columns.append('Day %s' % str(j-1))
nday_prices = pd.DataFrame(index=index, columns=nday_columns)

# Fill target dataframe
for i in range(periods):
    for j in range(target_days):
        nday_prices.iloc[i]['Day %s' % str(j)] = bp.iloc[i+days+j]['Adj. Close']
nday_prices

              Day 0    Day 1    Day 2    Day 3    Day 4    Day 5    Day 6
1977-01-12  1.93223  1.97777  1.95175  1.95826  1.94863   2.0103  1.97777
1977-01-13  1.97777  1.95175  1.95826  1.94863   2.0103  1.97777  1.96789
1977-01-14  1.95175  1.95826  1.94863   2.0103  1.97777  1.96789  1.99079
1977-01-15  1.95826  1.94863   2.0103  1.97777  1.96789  1.99079  1.99391
1977-01-16  1.94863   2.0103  1.97777  1.96789  1.99079  1.99391   2.0038
1977-01-17   2.0103  1.97777  1.96789  1.99079  1.99391   2.0038  2.00068
1977-01-18  1.97777  1.96789  1.99079  1.99391   2.0038  2.00068   2.0038
1977-01-19  1.96789  1.99079  1.99391   2.0038  2.00068   2.0038  1.99079
1977-01-20  1.99079  1.99391   2.0038  2.00068   2.0038  1.99079  1.99729
1977-01-21  1.99391   2.0038  2.00068   2.0038  1.99079  1.99729  1.99729
1977-01-22   2.0038  2.00068   2.0038  1.99079  1.99729  1.99729  1.99391
1977-01-23  2.00068   2.0038  1.99079  1.99729  1.99729  1.99391  2.00692
1977-01-24   2.0038  1.99079  1.99729  1.99729  1.99391  2.00692  2.03633
1977-01-25  1.99079  1.99729  1.99729  1.99391  2.00692  2.03633  2.10139
1977-01-26  1.99729  1.99729  1.99391  2.00692  2.03633  2.10139  2.17295
1977-01-27  1.99729  1.99391  2.00692  2.03633  2.10139  2.17295  2.19247
1977-01-28  1.99391  2.00692  2.03633  2.10139  2.17295  2.19247  2.19247
1977-01-29  2.00692  2.03633  2.10139  2.17295  2.19247  2.19247  2.17946
1977-01-30  2.03633  2.10139  2.17295  2.19247  2.19247  2.17946  2.18596
1977-01-31  2.10139  2.17295  2.19247  2.19247  2.17946  2.18596  2.16644
1977-02-01  2.17295  2.19247  2.19247  2.17946  2.18596  2.16644  2.12741
1977-02-02  2.19247  2.19247  2.17946  2.18596  2.16644  2.12741  2.12741
1977-02-03  2.19247  2.17946  2.18596  2.16644  2.12741  2.12741   2.1144
1977-02-04  2.17946  2.18596  2.16644  2.12741  2.12741   2.1144   2.1144
1977-02-05  2.18596  2.16644  2.12741  2.12741   2.1144   2.1144  2.08837
1977-02-06  2.16644  2.12741  2.12741   2.1144   2.1144  2.08837  2.09176
1977-02-07  2.12741  2.12741   2.1144   2.1144  2.08837  2.09176  2.09488
1977-02-08  2.12741   2.1144   2.1144  2.08837  2.09176  2.09488   2.1209
1977-02-09   2.1144   2.1144  2.08837  2.09176  2.09488   2.1209   2.1438
1977-02-10   2.1144  2.08837  2.09176  2.09488   2.1209   2.1438  2.16306
...             ...      ...      ...      ...      ...      ...      ...
2001-08-04  31.7411  31.9399  31.7808    32.64    32.99  33.8094  33.9844
2001-08-05  31.9399  31.7808    32.64    32.99  33.8094  33.9844  33.9683
2001-08-06  31.7808    32.64    32.99  33.8094  33.9844  33.9683  34.1131
2001-08-07    32.64    32.99  33.8094  33.9844  33.9683  34.1131  33.8637
2001-08-08    32.99  33.8094  33.9844  33.9683  34.1131  33.8637  33.9361
2001-08-09  33.8094  33.9844  33.9683  34.1131  33.8637  33.9361  34.1453
2001-08-10  33.9844  33.9683  34.1131  33.8637  33.9361  34.1453  34.3947
2001-08-11  33.9683  34.1131  33.8637  33.9361  34.1453  34.3947  34.3706
2001-08-12  34.1131  33.8637  33.9361  34.1453  34.3947  34.3706  34.3465
2001-08-13  33.8637  33.9361  34.1453  34.3947  34.3706  34.3465  34.1131
2001-08-14  33.9361  34.1453  34.3947  34.3706  34.3465  34.1131  34.3062
2001-08-15  34.1453  34.3947  34.3706  34.3465  34.1131  34.3062  33.9925
2001-08-16  34.3947  34.3706  34.3465  34.1131  34.3062  33.9925  33.9442
2001-08-17  34.3706  34.3465  34.1131  34.3062  33.9925  33.9442  33.9522
2001-08-18  34.3465  34.1131  34.3062  33.9925  33.9442  33.9522  33.9361
2001-08-19  34.1131  34.3062  33.9925  33.9442  33.9522  33.9361  33.7672
2001-08-20  34.3062  33.9925  33.9442  33.9522  33.9361  33.7672  33.7189
2001-08-21  33.9925  33.9442  33.9522  33.9361  33.7672  33.7189  33.8396
2001-08-22  33.9442  33.9522  33.9361  33.7672  33.7189  33.8396  33.4936
2001-08-23  33.9522  33.9361  33.7672  33.7189  33.8396  33.4936  32.4719
2001-08-24  33.9361  33.7672  33.7189  33.8396  33.4936  32.4719  33.1316
2001-08-25  33.7672  33.7189  33.8396  33.4936  32.4719  33.1316   33.735
2001-08-26  33.7189  33.8396  33.4936  32.4719  33.1316   33.735  33.8235
2001-08-27  33.8396  33.4936  32.4719  33.1316   33.735  33.8235  34.2499
2001-08-28  33.4936  32.4719  33.1316   33.735  33.8235  34.2499   34.258
2001-08-29  32.4719  33.1316   33.735  33.8235  34.2499   34.258  35.0947
2001-08-30  33.1316   33.735  33.8235  34.2499   34.258  35.0947  35.2878
2001-08-31   33.735  33.8235  34.2499   34.258  35.0947  35.2878  34.8131
2001-09-01  33.8235  34.2499   34.258  35.0947  35.2878  34.8131  34.4913
2001-09-02  34.2499   34.258  35.0947  35.2878  34.8131  34.4913  34.6683

[9000 rows x 7 columns]

In [32]:
# Train-test split (predict prices one day ahead)
def train_test_split_noshuffle(X, y, test_size=0.2):
    if len(X) != len(y):
        return "Error"
    split_index = int(len(X) * (1-test_size))
    X_train = X[:split_index]
    X_test = X[split_index:]
    y_train = y[:split_index]
    y_test = y[split_index:]
    return X_train, X_test, y_train, y_test

X_train, X_test, y_train, y_test = train_test_split_noshuffle(features, prices, test_size=0.2)

print("Train shapes (X,y): ", X_train.shape, y_train.shape)
print("Test shapes (X,y): ", X_test.shape, y_test.shape)

Train shapes (X,y):  (7200, 9) (7200, 1)
Test shapes (X,y):  (1800, 9) (1800, 1)

In [36]:
# Train-test split (predict prices `target_days` days ahead)

Xnd_train, Xnd_test, ynd_train, ynd_test = train_test_split_noshuffle(features, nday_prices, test_size=0.2)

print("Train shapes (Xnd,ynd): ", Xnd_train.shape, ynd_train.shape)
print("Test shapes (Xnd,ynd): ", Xnd_test.shape, ynd_test.shape)

Train shapes (Xnd,ynd):  (7200, 9) (7200, 7)
Test shapes (Xnd,ynd):  (1800, 9) (1800, 7)

### 2.2 Classifier

In [ ]:
# Classifier

from sklearn import svm
# clf = svm.SVR()

from sklearn.multioutput import MultiOutputRegressor
clf = MultiOutputRegressor(svm.SVR(random_state=0))

clf.fit(Xnd_train, ynd_train)
pred = clf.predict(Xnd_test)